### PR TITLE
Make sure rake is installed

### PR DESCRIPTION
**Pull request by patcon**

### CODE REVIEW

**Comment by pwelch** [comment]
@patcon Thanks for the Pull Request. I merged it, bumped the version number and added you to the contributors list.

**Comment by patcon** [comment]
Awesome! Thanks man

**Comment by patcon** [comment]
So wait, any reason you don't want to publish to opscode before someone else takes the namespace? Also, git tags would be helpful for releases going forward, as it makes the cheffile/berksfile more legible :)

**Comment by pwelch** [comment]
No good reason. I always felt the cookbook needed more work but I can publish as is.  I have a simple chef spec branch I want to merge in first. I will try and publish it in the next few days.

**Comment by patcon** [comment]
No hey, it's great. Thanks very much for putting it out there

**Comment by pwelch** [comment]
@patcon Sorry for the delay. I pushed it to the community site [here](http://community.opscode.com/cookbooks/janus) so you should be able to pull in updates from there in the future.

**Pull request merged**
